packages:
  - makerkit/nextjs-saas-starter-kit-lite/packages/**
  - makerkit/nextjs-saas-starter-kit-lite/tooling/*
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - supabase

