packages:
  - makerkit/nextjs-saas-starter-kit-lite/packages/**
  - makerkit/nextjs-saas-starter-kit-lite/tooling/*
  - packages/*
  - apps/*
  - "!apps/realestate"
  - "!apps/vehicles"

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - ffmpeg-static
  - supabase

