import Capacitor
import UIKit

/// Registers app-local plugins that `cap sync` doesn't know about.
///
/// `packageClassList` in capacitor.config.json is regenerated by `cap sync`
/// from npm plugins only, so StoreKitPlugin (which lives in this package) is
/// never listed there. Without explicit registration every `StoreKit.*` call
/// from JS rejects with "plugin is not implemented on ios".
public class ProvenanceBridgeViewController: CAPBridgeViewController {
    override public func capacitorDidLoad() {
        bridge?.registerPluginInstance(StoreKitPlugin())
    }
}
