import { PDFDocument, StandardFonts, type PDFFont, type PDFPage } from 'pdf-lib';

function wrapLines(text: string, maxChars: number): string[] {
  const normalized = text.replace(/\r\n/g, '\n').trim() || '—';
  const paragraphs = normalized.split('\n');
  const lines: string[] = [];
  for (const para of paragraphs) {
    const words = para.split(/\s+/).filter(Boolean);
    let current = '';
    for (const w of words) {
      const next = current ? `${current} ${w}` : w;
      if (next.length <= maxChars) {
        current = next;
      } else {
        if (current) lines.push(current);
        if (w.length > maxChars) {
          for (let i = 0; i < w.length; i += maxChars) {
            lines.push(w.slice(i, i + maxChars));
          }
          current = '';
        } else {
          current = w;
        }
      }
    }
    if (current) lines.push(current);
  }
  return lines.length ? lines : ['—'];
}

function drawParagraph(
  page: PDFPage,
  font: PDFFont,
  text: string,
  x: number,
  yStart: number,
  size: number,
  maxWidthChars: number,
  lineHeight: number,
): number {
  let y = yStart;
  for (const line of wrapLines(text, maxWidthChars)) {
    page.drawText(line, { x, y, size, font, maxWidth: 520 });
    y -= lineHeight;
  }
  return y;
}

export async function buildInvoicePdfBytes(input: {
  invoiceNumber: string;
  clientName: string;
  clientEmail: string | null;
  status: string;
  currency: string;
  dueDate: string | null;
  notes: string | null;
  taxCents: number;
  lines: { description: string; quantity: number; unitAmountCents: number }[];
}): Promise<Uint8Array> {
  const subtotalCents = input.lines.reduce(
    (sum, l) => sum + Math.round(l.quantity * l.unitAmountCents),
    0,
  );
  const totalCents = subtotalCents + input.taxCents;
  const fmt = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: input.currency || 'USD',
  });

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let y = 740;
  page.drawText('Invoice', { x: 50, y, size: 22, font: fontBold });
  y -= 36;
  page.drawText(`Invoice # ${input.invoiceNumber}`, { x: 50, y, size: 12, font: fontBold });
  y -= 18;
  page.drawText(`Bill to: ${input.clientName}`, { x: 50, y, size: 11, font });
  y -= 14;
  if (input.clientEmail) {
    page.drawText(input.clientEmail, { x: 50, y, size: 10, font });
    y -= 14;
  }
  page.drawText(`Status: ${input.status}`, { x: 50, y, size: 10, font });
  y -= 14;
  if (input.dueDate) {
    page.drawText(`Due: ${input.dueDate}`, { x: 50, y, size: 10, font });
    y -= 14;
  }
  y -= 16;
  page.drawText('Line items', { x: 50, y, size: 12, font: fontBold });
  y -= 20;
  page.drawText('Description', { x: 50, y, size: 9, font: fontBold });
  page.drawText('Qty', { x: 320, y, size: 9, font: fontBold });
  page.drawText('Unit', { x: 380, y, size: 9, font: fontBold });
  page.drawText('Amount', { x: 470, y, size: 9, font: fontBold });
  y -= 14;

  let drawPage: PDFPage = page;
  for (const line of input.lines) {
    const descLines = wrapLines(line.description, 42);
    const amount = Math.round(line.quantity * line.unitAmountCents);
    let first = true;
    for (const dl of descLines) {
      if (y < 100) {
        drawPage = pdfDoc.addPage([612, 792]);
        y = 740;
      }
      drawPage.drawText(dl, { x: 50, y, size: 9, font });
      if (first) {
        drawPage.drawText(String(line.quantity), { x: 320, y, size: 9, font });
        drawPage.drawText(fmt.format(line.unitAmountCents / 100), { x: 380, y, size: 9, font });
        drawPage.drawText(fmt.format(amount / 100), { x: 470, y, size: 9, font });
      }
      y -= 12;
      first = false;
    }
  }

  if (y < 100) {
    drawPage = pdfDoc.addPage([612, 792]);
    y = 740;
  }
  y -= 8;
  drawPage.drawText(`Subtotal: ${fmt.format(subtotalCents / 100)}`, { x: 380, y, size: 10, font });
  y -= 14;
  drawPage.drawText(`Tax: ${fmt.format(input.taxCents / 100)}`, { x: 380, y, size: 10, font });
  y -= 14;
  drawPage.drawText(`Total: ${fmt.format(totalCents / 100)}`, { x: 380, y, size: 11, font: fontBold });

  if (input.notes?.trim()) {
    y -= 28;
    if (y < 120) {
      drawPage = pdfDoc.addPage([612, 792]);
      y = 740;
    }
    drawPage.drawText('Notes', { x: 50, y, size: 11, font: fontBold });
    y -= 14;
    y = drawParagraph(drawPage, font, input.notes, 50, y, 9, 90, 12);
  }

  drawPage.drawText('Generated by Provenance', { x: 50, y: 36, size: 8, font });

  return pdfDoc.save();
}

export async function buildLoanAgreementPdfBytes(input: {
  artworkTitle: string;
  borrowerName: string;
  borrowerEmail: string | null;
  lenderName: string | null;
  lenderEmail: string | null;
  startDate: string | null;
  endDate: string | null;
  termsText: string | null;
  conditionsText: string | null;
  insuranceText: string | null;
  status: string;
}): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let y = 740;
  page.drawText('Artwork loan agreement', { x: 50, y, size: 20, font: fontBold });
  y -= 28;
  page.drawText(`Artwork: ${input.artworkTitle}`, { x: 50, y, size: 11, font: fontBold });
  y -= 18;
  page.drawText(`Borrower: ${input.borrowerName}`, { x: 50, y, size: 10, font });
  y -= 14;
  if (input.borrowerEmail) {
    page.drawText(input.borrowerEmail, { x: 50, y, size: 10, font });
    y -= 14;
  }
  if (input.lenderName) {
    page.drawText(`Lender: ${input.lenderName}`, { x: 50, y, size: 10, font });
    y -= 14;
  }
  if (input.lenderEmail) {
    page.drawText(input.lenderEmail, { x: 50, y, size: 10, font });
    y -= 14;
  }
  if (input.startDate || input.endDate) {
    page.drawText(
      `Loan period: ${input.startDate ?? '—'} → ${input.endDate ?? '—'}`,
      { x: 50, y, size: 10, font },
    );
    y -= 14;
  }
  page.drawText(`Status: ${input.status}`, { x: 50, y, size: 10, font });
  y -= 22;

  const sections: { title: string; body: string | null }[] = [
    { title: 'Terms', body: input.termsText },
    { title: 'Conditions', body: input.conditionsText },
    { title: 'Insurance requirements', body: input.insuranceText },
  ];

  for (const s of sections) {
    if (y < 120) break;
    page.drawText(s.title, { x: 50, y, size: 12, font: fontBold });
    y -= 16;
    y = drawParagraph(page, font, s.body ?? '', 50, y, 9, 85, 12);
    y -= 10;
  }

  page.drawText('Generated by Provenance (MVP — obtain legal review before use.)', {
    x: 50,
    y: 36,
    size: 7,
    font,
  });

  return pdfDoc.save();
}
